networks:
  traefik_proxy:
    external: true

services:
  grafana:
    networks:
      - default
      - traefik_proxy
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.${SERVICE:-prometheus-grafana}.entrypoints=webs
      - traefik.http.routers.${SERVICE:-prometheus-grafana}.tls.certresolver=leresolver
      - traefik.http.routers.${SERVICE:-prometheus-grafana}.rule=Host(`${DOMAIN}`)
      - traefik.http.services.${SERVICE:-prometheus-grafana}.loadbalancer.server.port=${APP_PORT:-3000}
    
